distributor_id: "10094001"
name: "KARDAL INC DBA MEGAWHOLESALE"
address: "2682 BRENNER DR"
city: "DALLAS"
state: "TX"
zip_code: "75220"
country: "USA"
contact_last_name: "LIM"
contact_first_name: "LIZA"
contact_phone: "8178087618"
contact_email: "Liza@americajuiceco.com"
test_mode: true
